# Generated by Django 4.0.8 on 2022-11-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency_prices', '0002_alter_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_prices.currency'),
        ),
    ]
